name: Keep Server Alive

on:
  schedule:
    - cron: '*/1 * * * *' # ทุก 10 นาที

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping My Server
        run: curl -s https://back-end-y49i.onrender.com > /dev/null

